# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20160617_1800'),
        ('questions', '0001_initial_squashed_0005_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='attachments',
            field=models.ManyToManyField(to='files.File', verbose_name='attachments'),
        ),
    ]
