# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='attachments',
            field=models.ManyToManyField(to='files.File'),
        ),
    ]
