# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_topic_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='questions.Topic', verbose_name='topic'),
        ),
    ]
