# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topic_replies_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(default='', verbose_name='content'),
            preserve_default=False,
        ),
    ]
