# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, verbose_name='summary'),
        ),
    ]
