# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.IntegerField(default=2, verbose_name=[(1, 'company'), (2, 'government'), (3, 'media'), (4, 'finance'), (5, 'energy_and_raw_materials')]),
        ),
    ]
