# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 21:50
from __future__ import unicode_literals

import articles.consts
from django.db import migrations
import enhancements.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_summary_squashed_0003_auto_20160618_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=enhancements.models.fields.EnumField(articles.consts.ArticleType, choices=[(articles.consts.ArticleType(1), 'company'), (articles.consts.ArticleType(2), 'government'), (articles.consts.ArticleType(3), 'media'), (articles.consts.ArticleType(4), 'finance'), (articles.consts.ArticleType(5), 'energy_and_raw_materials'), (articles.consts.ArticleType(6), 'electronic_technology'), (articles.consts.ArticleType(7), 'bank'), (articles.consts.ArticleType(8), 'real_estate')], default=articles.consts.ArticleType(2), verbose_name='article type'),
        ),
    ]
