# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 10:55
from __future__ import unicode_literals

import articles.consts
from django.db import migrations
import enhancements.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=enhancements.models.fields.EnumField(articles.consts.ArticleType, choices=[(articles.consts.ArticleType(1), 'company'), (articles.consts.ArticleType(2), 'government'), (articles.consts.ArticleType(3), 'media'), (articles.consts.ArticleType(4), 'finance'), (articles.consts.ArticleType(5), 'energy_and_raw_materials')], default=articles.consts.ArticleType(2)),
        ),
    ]
