# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 02:45
from __future__ import unicode_literals

import articles.consts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enhancements.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20160610_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=enhancements.models.fields.EnumField(articles.consts.ArticleType, choices=[(articles.consts.ArticleType(1), 'company'), (articles.consts.ArticleType(2), 'government'), (articles.consts.ArticleType(3), 'media'), (articles.consts.ArticleType(4), 'finance'), (articles.consts.ArticleType(5), 'energy_and_raw_materials')], default=articles.consts.ArticleType(2), verbose_name='article type'),
        ),
        migrations.AlterField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(to='files.File', verbose_name='attachments'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='is top'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='articles.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
