# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160614_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='files.File', verbose_name='attachments'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.Tag', verbose_name='tags'),
        ),
    ]
