# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255, verbose_name='issuer')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'bond',
            },
        ),
        migrations.CreateModel(
            name='BondLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialized_data', jsonfield.fields.JSONField()),
                ('quantity', models.FloatField(verbose_name='quantity')),
                ('price', models.FloatField(verbose_name='price')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Bond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Futures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
            ],
            options={
                'verbose_name': 'futures',
            },
        ),
        migrations.CreateModel(
            name='FuturesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialized_data', jsonfield.fields.JSONField()),
                ('price', models.FloatField(verbose_name='price')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Futures')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('mining_costs', models.FloatField(verbose_name='mining costs')),
                ('processing_costs', models.FloatField(verbose_name='processing costs')),
                ('price', models.FloatField(verbose_name='costs')),
            ],
            options={
                'verbose_name': 'raw materials',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialized_data', jsonfield.fields.JSONField()),
                ('price', models.FloatField(verbose_name='costs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.RawMaterials')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('turnover', models.FloatField(verbose_name='turnover')),
            ],
            options={
                'verbose_name': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialized_data', jsonfield.fields.JSONField()),
                ('price', models.FloatField(verbose_name='price')),
                ('turnover', models.FloatField(verbose_name='turnover')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='current_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.StockLog'),
        ),
        migrations.AddField(
            model_name='rawmaterials',
            name='current_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.RawMaterialsLog'),
        ),
        migrations.AddField(
            model_name='futures',
            name='current_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.FuturesLog'),
        ),
        migrations.AddField(
            model_name='bond',
            name='current_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.BondLog'),
        ),
    ]
