# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='current_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.BondLog'),
        ),
        migrations.AlterField(
            model_name='futures',
            name='current_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.FuturesLog'),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='current_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.RawMaterialsLog'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.StockLog'),
        ),
    ]
