# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20160501_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bond',
            options={'verbose_name': 'bond', 'verbose_name_plural': 'bonds'},
        ),
        migrations.AlterModelOptions(
            name='futures',
            options={'verbose_name': 'futures', 'verbose_name_plural': 'futures'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterials',
            options={'verbose_name': 'raw materials', 'verbose_name_plural': 'raw materials'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'stock', 'verbose_name_plural': 'stocks'},
        ),
    ]
