# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20160507_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='company_info',
            field=models.TextField(default='', verbose_name='company info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='comments',
            field=models.ManyToManyField(to='finance.Comment', verbose_name='brokerage comments'),
        ),
    ]
