# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20160617_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='turnover',
        ),
        migrations.RemoveField(
            model_name='stocklog',
            name='turnover',
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.FloatField(default=0, verbose_name='volume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklog',
            name='volume',
            field=models.FloatField(default=0, verbose_name='volume'),
            preserve_default=False,
        ),
    ]
