# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20160617_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='comments',
            field=models.ManyToManyField(blank=True, to='finance.Comment', verbose_name='brokerage comments'),
        ),
    ]
