# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20160711_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.Stock'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='current_log',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.BondLog'),
        ),
        migrations.AlterField(
            model_name='futures',
            name='current_log',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.FuturesLog'),
        ),
        migrations.AlterField(
            model_name='rawmaterials',
            name='current_log',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.RawMaterialsLog'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_log',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.StockLog'),
        ),
    ]
