# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20160711_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondlog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.Bond'),
        ),
        migrations.AlterField(
            model_name='futureslog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.Futures'),
        ),
        migrations.AlterField(
            model_name='rawmaterialslog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.RawMaterials'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.Stock'),
        ),
    ]
