require('expose?jQuery!jquery')
require('expose?Tether!tether')
require('expose?_!lodash')
require('expose?Vue!vue')
require('bootstrap/dist/js/bootstrap.min.js')
require('bower_components/qiniu/dist/qiniu.min.js')