# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('accounts', '0001_squashed_0004_auto_20160430_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reports',
            field=models.ManyToManyField(to='files.File'),
        ),
    ]
