# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0002_userdata_reports'), ('accounts', '0003_user_bureau_type')]

    dependencies = [
        ('accounts', '0001_squashed_0004_auto_20160430_1245'),
        ('files', '0001_initial_squashed_0005_auto_20160616_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='reports',
            field=models.ManyToManyField(to='files.File'),
        ),
        migrations.AddField(
            model_name='user',
            name='bureau_type',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'real_estate'), (3, 'car'), (4, 'electronic_technology'), (5, 'bank'), (6, 'enegry_and_raw_materials'), (7, 'financial_system'), (8, 'media')], default=1),
        ),
    ]
