# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:26
from __future__ import unicode_literals

import accounts.consts
from django.db import migrations, models
import django.db.models.deletion
import enhancements.models.fields


class Migration(migrations.Migration):

    replaces = [('accounts', '0003_auto_20160502_0414'), ('accounts', '0004_auto_20160507_1039'), ('accounts', '0005_auto_20160507_1228'), ('accounts', '0006_auto_20160507_2153'), ('accounts', '0007_auto_20160610_1843'), ('accounts', '0008_auto_20160610_1855'), ('accounts', '0009_auto_20160613_1053'), ('accounts', '0010_auto_20160614_1045')]

    dependencies = [
        ('accounts', '0002_userdata_reports_squashed_0003_user_bureau_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'user data', 'verbose_name_plural': 'user data'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
        migrations.AlterField(
            model_name='user',
            name='bureau_type',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'real_estate'), (3, 'car'), (4, 'electronic_technology'), (5, 'bank'), (6, 'enegry_and_raw_materials'), (7, 'financial_system'), (8, 'media')], default=1, verbose_name='bureau type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'government'), (2, 'company'), (3, 'bureau')], default=2, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='reports',
            field=models.ManyToManyField(related_name='reports', to='files.File'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sector',
            field=models.CharField(max_length=255, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='industry',
            field=models.CharField(blank=True, max_length=255, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='reports',
            field=models.ManyToManyField(blank=True, to='files.File', verbose_name='reports'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sector',
            field=models.CharField(blank=True, max_length=255, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bureau_type',
            field=enhancements.models.fields.EnumField(accounts.consts.BureauType, choices=[(1, 'none'), (2, 'real_estate'), (3, 'car'), (4, 'electronic_technology'), (5, 'bank'), (6, 'enegry_and_raw_materials'), (7, 'financial_system'), (8, 'media')], default=accounts.consts.BureauType(1), verbose_name='bureau type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=enhancements.models.fields.EnumField(accounts.consts.UserType, choices=[(1, 'government'), (2, 'company'), (3, 'bureau')], default=accounts.consts.UserType(2), verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bureau_type',
            field=enhancements.models.fields.EnumField(accounts.consts.BureauType, choices=[(accounts.consts.BureauType(1), 'none'), (accounts.consts.BureauType(2), 'real_estate'), (accounts.consts.BureauType(3), 'car'), (accounts.consts.BureauType(4), 'electronic_technology'), (accounts.consts.BureauType(5), 'bank'), (accounts.consts.BureauType(6), 'enegry_and_raw_materials'), (accounts.consts.BureauType(7), 'financial_system'), (accounts.consts.BureauType(8), 'media')], default=accounts.consts.BureauType(1), verbose_name='bureau type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=enhancements.models.fields.EnumField(accounts.consts.UserType, choices=[(accounts.consts.UserType(1), 'government'), (accounts.consts.UserType(2), 'company'), (accounts.consts.UserType(3), 'bureau')], default=accounts.consts.UserType(2), verbose_name='user type'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserData', verbose_name='user data'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bureau_type',
            field=enhancements.models.fields.EnumField(accounts.consts.BureauType, choices=[(accounts.consts.BureauType(1), 'none'), (accounts.consts.BureauType(2), 'real_estate'), (accounts.consts.BureauType(3), 'car'), (accounts.consts.BureauType(4), 'electronic_technology'), (accounts.consts.BureauType(5), 'bank'), (accounts.consts.BureauType(6), 'enegry_and_raw_materials'), (accounts.consts.BureauType(7), 'financial_system'), (accounts.consts.BureauType(8), 'media')], default=accounts.consts.BureauType(1), editable=False, verbose_name='bureau type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=enhancements.models.fields.EnumField(accounts.consts.UserType, choices=[(accounts.consts.UserType(1), 'government'), (accounts.consts.UserType(2), 'company'), (accounts.consts.UserType(3), 'bureau')], default=accounts.consts.UserType(2), editable=False, verbose_name='user type'),
        ),
    ]
