# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 04:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata_reports_squashed_0003_user_bureau_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'user data', 'verbose_name_plural': 'user data'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='data',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='bureau_type',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'real_estate'), (3, 'car'), (4, 'electronic_technology'), (5, 'bank'), (6, 'enegry_and_raw_materials'), (7, 'financial_system'), (8, 'media')], default=1, verbose_name='bureau type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'government'), (2, 'company'), (3, 'bureau')], default=2, verbose_name='user type'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='reports',
            field=models.ManyToManyField(related_name='reports', to='files.File'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sector',
            field=models.CharField(max_length=255, verbose_name='sector'),
        ),
    ]
