# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdata_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bureau_type',
            field=models.IntegerField(choices=[(1, 'none'), (2, 'real_estate'), (3, 'car'), (4, 'electronic_technology'), (5, 'bank'), (6, 'enegry_and_raw_materials'), (7, 'financial_system'), (8, 'media')], default=1),
        ),
    ]
