# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'government'), (2, 'company'), (3, 'bureau')], default=2),
        ),
    ]
