# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 04:20
from __future__ import unicode_literals

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160617_2241'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserQuerySet.as_manager()),
            ],
        ),
    ]
