# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160507_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='industry',
            field=models.CharField(blank=True, max_length=255, verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='reports',
            field=models.ManyToManyField(blank=True, to='files.File', verbose_name='reports'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sector',
            field=models.CharField(blank=True, max_length=255, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
