# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 10:43
from __future__ import unicode_literals

import accounts.consts
from django.db import migrations
import enhancements.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160507_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bureau_type',
            field=enhancements.models.fields.EnumField(accounts.consts.BureauType, choices=[(1, 'none'), (2, 'real_estate'), (3, 'car'), (4, 'electronic_technology'), (5, 'bank'), (6, 'enegry_and_raw_materials'), (7, 'financial_system'), (8, 'media')], default=accounts.consts.BureauType(1), verbose_name='bureau type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=enhancements.models.fields.EnumField(accounts.consts.UserType, choices=[(1, 'government'), (2, 'company'), (3, 'bureau')], default=accounts.consts.UserType(2), verbose_name='user type'),
        ),
    ]
