# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=4096)),
                ('storage_url', models.URLField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('mime_type', models.CharField(max_length=255)),
                ('file_type', models.IntegerField(choices=[(1, 'video'), (2, 'image'), (3, 'file')])),
            ],
        ),
    ]
