# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial_squashed_0005_auto_20160616_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=4096, verbose_name='file path'),
        ),
    ]
