# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20160616_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default='', max_length=4096, verbose_name='file path'),
            preserve_default=False,
        ),
    ]
