# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=4096, verbose_name='file name'),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='mime type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='storage_url',
            field=models.URLField(blank=True, verbose_name='url'),
        ),
    ]
