# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20160430_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='module',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
