# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='module',
            field=models.CharField(max_length=255, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
    ]
